import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { after, describe, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import {
  decideMerge,
  hasConflictMarkers,
  materializeZonesForMerge,
  mergeIndex,
  readZoneTexts,
} from '../lib/merge-index.mjs'
import { removeDirsWithRetry } from './helpers.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.dirname(__dirname)
const BIN = path.join(REPO_ROOT, 'bin', 'atlas.mjs')

const tmpDirs = []

after(async () => {
  await removeDirsWithRetry(tmpDirs)
})

function mkTmp(prefix) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix))
  tmpDirs.push(dir)
  return dir
}

function git(cwd, args, opts = {}) {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    ...opts,
  })
}

function mkGitRepo() {
  const dir = mkTmp('atlas-merge-idx-')
  git(dir, ['init', '-q'])
  git(dir, ['config', 'user.email', 'test@example.com'])
  git(dir, ['config', 'user.name', 'Test'])
  // Avoid ambiguous default-branch names across git versions.
  git(dir, ['checkout', '-b', 'main'])
  return dir
}

function writeMinimalVault(repo, vaultName = 'atlas') {
  const vault = path.join(repo, vaultName)
  fs.mkdirSync(path.join(vault, 'map', 'zones'), { recursive: true })
  fs.writeFileSync(
    path.join(repo, 'atlas.config.json'),
    JSON.stringify({ vaultDir: vaultName }, null, 2) + '\n',
  )
  fs.writeFileSync(path.join(vault, 'map', 'index.md'), '<!-- GENERATED -->\n# empty\n')
  return vault
}

function zoneCard(slug, summary = `zone ${slug}`) {
  return `---
type: zone
summary: "${summary}"
tags: []
status: seeded
created: 2026-07-09
updated: 2026-07-09
verifiedAt: unverified
owns:
  globs:
    - "src/${slug}/**"
  routes: []
  testids: []
  tools: []
depends: []
invariants: []
skills: []
advances: []
related: []
sources: []
---

## What this is

${summary}
`
}

function writeZone(vault, slug, summary) {
  fs.mkdirSync(path.join(vault, 'map', 'zones'), { recursive: true })
  fs.writeFileSync(path.join(vault, 'map', 'zones', `${slug}.md`), zoneCard(slug, summary))
}

test('hasConflictMarkers finds all three git markers', () => {
  assert.equal(hasConflictMarkers('a\n<<<<<<< HEAD\nb\n'), true)
  assert.equal(hasConflictMarkers('a\n=======\nb\n'), true)
  assert.equal(hasConflictMarkers('a\n>>>>>>> branch\nb\n'), true)
  assert.equal(hasConflictMarkers('a\nnormal text\nb\n'), false)
})

test('a table row that merely starts with = is not a conflict marker', () => {
  assert.equal(hasConflictMarkers('| zone | =====not a marker |\n'), false)
})

test('decideMerge refuses when a zone card is conflicted', () => {
  const r = decideMerge({ zoneTexts: ['ok', '<<<<<<< HEAD\nx'] })
  assert.equal(r.ok, false)
  assert.match(r.reason, /zone/i)
})

test('decideMerge regenerates when zones are clean', () => {
  const r = decideMerge({ zoneTexts: ['ok', 'also ok'] })
  assert.equal(r.ok, true)
  assert.equal(r.action, 'regenerate')
})

describe('mergeIndex regeneration', () => {
  test('driver regenerates a deterministic index from the same zone set', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'alpha', 'alpha zone')
    writeZone(vault, 'beta', 'beta zone')
    // Tracked stubs so owns.globs resolve under real git resolvers if used
    fs.mkdirSync(path.join(repo, 'src', 'alpha'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'alpha', 'a.js'), 'export {}\n')
    fs.mkdirSync(path.join(repo, 'src', 'beta'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'beta', 'b.js'), 'export {}\n')

    const rendered = '<!-- GENERATED by atlas build — do not hand-edit. -->\n# Atlas Map — index\n| alpha |\n| beta |\n'
    const calls = []
    const ours1 = path.join(repo, 'ours1.md')
    const ours2 = path.join(repo, 'ours2.md')
    fs.writeFileSync(ours1, 'stale-left\n')
    fs.writeFileSync(ours2, 'stale-right\n')

    const r1 = mergeIndex({
      ours: ours1,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => {
        calls.push(1)
        return { rendered, indexPath: path.join(vault, 'map', 'index.md') }
      },
    })
    const r2 = mergeIndex({
      ours: ours2,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => {
        calls.push(2)
        return { rendered, indexPath: path.join(vault, 'map', 'index.md') }
      },
    })

    assert.equal(r1.ok, true)
    assert.equal(r2.ok, true)
    assert.equal(fs.readFileSync(ours1, 'utf8'), rendered)
    assert.equal(fs.readFileSync(ours2, 'utf8'), rendered)
    assert.equal(fs.readFileSync(ours1, 'utf8'), fs.readFileSync(ours2, 'utf8'))
    assert.deepEqual(calls, [1, 2])
  })

  test('driver fails loudly (nonzero path) with no partial write when render errors', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'solo', 'solo')
    const ours = path.join(repo, 'ours-fail.md')
    const sentinel = 'DO NOT TOUCH\n'
    fs.writeFileSync(ours, sentinel)

    const r = mergeIndex({
      ours,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => null,
    })
    assert.equal(r.ok, false)
    assert.match(r.reason, /render failed/i)
    assert.equal(fs.readFileSync(ours, 'utf8'), sentinel)

    const rThrow = mergeIndex({
      ours,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => {
        throw new Error('boom')
      },
    })
    assert.equal(rThrow.ok, false)
    assert.match(rThrow.reason, /render threw|boom/i)
    assert.equal(fs.readFileSync(ours, 'utf8'), sentinel)
  })

  test('empty render with zones on disk refuses and does not overwrite (F3)', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'solo', 'solo')
    const ours = path.join(repo, 'ours-empty.md')
    const sentinel = 'GOOD INDEX\n'
    fs.writeFileSync(ours, sentinel)

    const r = mergeIndex({
      ours,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => ({ rendered: '', indexPath: path.join(vault, 'map', 'index.md') }),
    })
    assert.equal(r.ok, false)
    assert.match(r.reason, /empty render/i)
    assert.equal(fs.readFileSync(ours, 'utf8'), sentinel)
  })

  test('empty render with zero zones is allowed (empty vault is legitimate)', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    // no zones
    const ours = path.join(repo, 'ours-empty-vault.md')
    fs.writeFileSync(ours, 'stale\n')
    const r = mergeIndex({
      ours,
      repoRoot: repo,
      zonesDir: path.join(vault, 'map', 'zones'),
      materialize: false,
      render: () => ({ rendered: '', indexPath: path.join(vault, 'map', 'index.md') }),
    })
    assert.equal(r.ok, true)
    assert.equal(fs.readFileSync(ours, 'utf8'), '')
  })

  test('unit: materialize refuses when parents disagree and WT is first-parent only (F1)', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'shared', 'HEAD-VERSION')
    fs.mkdirSync(path.join(repo, 'src', 'shared'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'shared', 'x.js'), 'export {}\n')
    git(repo, ['add', 'atlas.config.json', 'atlas', 'src'])
    git(repo, ['commit', '-q', '-m', 'base'])

    git(repo, ['checkout', '-q', '-b', 'side'])
    writeZone(vault, 'shared', 'MERGE-VERSION')
    git(repo, ['add', 'atlas/map/zones/shared.md'])
    git(repo, ['commit', '-q', '-m', 'side rewrites shared'])

    git(repo, ['checkout', '-q', 'main'])
    // Simulate mid-merge: MERGE_HEAD present, WT still holds HEAD clean copy
    const sideSha = git(repo, ['rev-parse', 'side']).trim()
    fs.writeFileSync(path.join(repo, '.git', 'MERGE_HEAD'), `${sideSha}\n`)
    // WT is HEAD version (no markers)
    assert.match(fs.readFileSync(path.join(vault, 'map', 'zones', 'shared.md'), 'utf8'), /HEAD-VERSION/)

    const mat = materializeZonesForMerge(repo, path.join(vault, 'map', 'zones'))
    assert.equal(mat.conflicted, true, 'must refuse first-parent-only when parents disagree')
  })

  test('e2e: real git merge with driver configured as a user would — both zones, exit 0, no markers (F2)', () => {
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'base-zone', 'shared base')
    fs.mkdirSync(path.join(repo, 'src', 'base-zone'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'base-zone', 'x.js'), 'export {}\n')
    fs.writeFileSync(
      path.join(vault, 'map', 'index.md'),
      '<!-- GENERATED by atlas build — do not hand-edit. -->\n# Atlas Map — index\n| base-zone |\n',
    )
    git(repo, ['add', 'atlas.config.json', 'atlas', 'src'])
    git(repo, ['commit', '-q', '-m', 'base'])

    // Wire merge driver the way docs describe: .gitattributes + local git config
    // (never global). This is the real consumer path.
    const driver = `node ${JSON.stringify(BIN)} merge-index %O %A %B %L %P`
    git(repo, ['config', 'merge.atlas-index.name', 'regenerate Atlas map/index.md'])
    git(repo, ['config', 'merge.atlas-index.driver', driver])
    fs.writeFileSync(path.join(repo, '.gitattributes'), 'atlas/map/index.md merge=atlas-index\n')
    git(repo, ['add', '.gitattributes'])
    git(repo, ['commit', '-q', '-m', 'attrs'])

    // Branch A adds zone-a and rewrites index
    git(repo, ['checkout', '-q', '-b', 'branch-a'])
    writeZone(vault, 'zone-a', 'from A')
    fs.mkdirSync(path.join(repo, 'src', 'zone-a'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'zone-a', 'a.js'), 'export {}\n')
    fs.writeFileSync(
      path.join(vault, 'map', 'index.md'),
      '<!-- GENERATED by atlas build — do not hand-edit. -->\n# Atlas Map — index\n| base-zone |\n| zone-a |\n',
    )
    git(repo, ['add', 'atlas/map/zones/zone-a.md', 'atlas/map/index.md', 'src/zone-a'])
    git(repo, ['commit', '-q', '-m', 'A adds zone-a'])

    // Branch B from main
    git(repo, ['checkout', '-q', 'main'])
    git(repo, ['checkout', '-q', '-b', 'branch-b'])
    writeZone(vault, 'zone-b', 'from B')
    fs.mkdirSync(path.join(repo, 'src', 'zone-b'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'zone-b', 'b.js'), 'export {}\n')
    fs.writeFileSync(
      path.join(vault, 'map', 'index.md'),
      '<!-- GENERATED by atlas build — do not hand-edit. -->\n# Atlas Map — index\n| base-zone |\n| zone-b |\n',
    )
    git(repo, ['add', 'atlas/map/zones/zone-b.md', 'atlas/map/index.md', 'src/zone-b'])
    git(repo, ['commit', '-q', '-m', 'B adds zone-b'])

    // Real consumer path: git merge must succeed
    const merge = spawnSync('git', ['merge', '--no-edit', 'branch-a'], {
      cwd: repo,
      encoding: 'utf8',
    })
    assert.equal(
      merge.status,
      0,
      `git merge must exit 0 (driver path). stdout=${merge.stdout}\nstderr=${merge.stderr}`,
    )

    // Index on disk after the real merge (not a hand-invoked driver)
    const indexText = fs.readFileSync(path.join(vault, 'map', 'index.md'), 'utf8')
    assert.equal(
      hasConflictMarkers(indexText),
      false,
      `index still has conflict markers:\n${indexText}`,
    )
    assert.match(indexText, /zone-a/, 'index after merge must list zone-a')
    assert.match(indexText, /zone-b/, 'index after merge must list zone-b')
    assert.match(indexText, /base-zone/, 'index after merge must list base-zone')

    // Both zone cards present
    assert.ok(fs.existsSync(path.join(vault, 'map', 'zones', 'zone-a.md')))
    assert.ok(fs.existsSync(path.join(vault, 'map', 'zones', 'zone-b.md')))

    // No conflict markers anywhere in the tree
    const walk = (dir) => {
      for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        if (ent.name === '.git') continue
        const p = path.join(dir, ent.name)
        if (ent.isDirectory()) walk(p)
        else if (ent.name.endsWith('.md') || ent.name.endsWith('.js') || ent.name.endsWith('.json')) {
          const t = fs.readFileSync(p, 'utf8')
          assert.equal(hasConflictMarkers(t), false, `markers in ${p}`)
        }
      }
    }
    walk(repo)
  })

  test('unit: hand-invoked merge-index CLI regenerates from on-disk zones', () => {
    // Separate from the e2e git-merge test — proves the CLI entrypoint alone.
    const repo = mkGitRepo()
    const vault = writeMinimalVault(repo)
    writeZone(vault, 'base-zone', 'shared base')
    writeZone(vault, 'zone-a', 'from A')
    writeZone(vault, 'zone-b', 'from B')
    fs.mkdirSync(path.join(repo, 'src', 'base-zone'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'base-zone', 'x.js'), 'export {}\n')
    fs.mkdirSync(path.join(repo, 'src', 'zone-a'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'zone-a', 'a.js'), 'export {}\n')
    fs.mkdirSync(path.join(repo, 'src', 'zone-b'), { recursive: true })
    fs.writeFileSync(path.join(repo, 'src', 'zone-b', 'b.js'), 'export {}\n')
    git(repo, ['add', 'atlas.config.json', 'atlas', 'src'])
    git(repo, ['commit', '-q', '-m', 'zones'])

    const ours = path.join(repo, 'resolved-index.md')
    fs.writeFileSync(ours, 'conflicted\n')
    const mi = spawnSync(
      'node',
      [BIN, 'merge-index', '/dev/null', ours, '/dev/null', '7', 'atlas/map/index.md'],
      { cwd: repo, encoding: 'utf8' },
    )
    assert.equal(mi.status, 0, `merge-index failed: ${mi.stderr}`)
    const resolved = fs.readFileSync(ours, 'utf8')
    assert.match(resolved, /zone-a/)
    assert.match(resolved, /zone-b/)
    assert.match(resolved, /base-zone/)
    assert.equal(hasConflictMarkers(resolved), false)
  })
})
