import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { findRepoRoot, findVaultDir } from './detect.mjs'

const PACKAGE_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const TEMPLATES_DIR = path.join(PACKAGE_ROOT, 'templates')

const NOTE_TEMPLATE_NAMES = [
  'zone.md',
  'flow.md',
  'decision.md',
  'spec.md',
  'plan.md',
  'program.md',
  'idea.md',
  'debt.md',
  'pillar.md',
]

const CORE_DIRS = [
  'map/zones',
  'map/decisions',
  'specs',
  'plans',
  'ideas',
  'tech-debt',
  'templates',
]

const INDEX_PLACEHOLDER = `<!-- GENERATED by atlas — do not hand-edit -->

| Zone | Status | Freshness | Summary |
|------|--------|-----------|---------|
`

const BACKLOG_TEMPLATE = `# BACKLOG

Multi-session coordination. Claim a row with 🟡 before starting work on it,
record a **Lands** field (branch name, or \`docs→main\` for vault-only work),
and mark it ✅ with a reference once done.

Status legend: 🟡 claimed · ⬜ open · ✅ done

## Track A (main, sequential)

- [ ] **A1 — <mission>**

## Track D (side-missions, parallel-safe)

| ID | Status | Mission | Lands |
|----|--------|---------|-------|
`

const DRAFTS_README = `# drafts

Human scratch space. Excluded from agent retrieval by default (see
\`atlas.config.json\` → \`retrieval.excludeFromSearch\`).
`

const MODULE_ACTIONS = {
  flows: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'map', 'flows'), ctx)
  },
  programs: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'programs'), ctx)
  },
  vision: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'vision'), ctx)
  },
  reference: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'reference'), ctx)
  },
  archive: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'archive'), ctx)
  },
  backlog: (vaultDir, ctx) => {
    ensureFile(path.join(vaultDir, 'BACKLOG.md'), BACKLOG_TEMPLATE, ctx)
  },
  drafts: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, 'drafts'), ctx)
    ensureFile(path.join(vaultDir, 'drafts', 'README.md'), DRAFTS_README, ctx)
  },
}

const MODULE_NAMES = Object.keys(MODULE_ACTIONS)

function todayDate() {
  return new Date().toISOString().slice(0, 10)
}

function ensureDir(dirPath, { dryRun, log, relBase }) {
  const rel = `${path.relative(relBase, dirPath)}/`
  if (fs.existsSync(dirPath)) {
    log(`exists, skipping: ${rel}`)
    return
  }
  if (dryRun) {
    log(`would create: ${rel}`)
    return
  }
  fs.mkdirSync(dirPath, { recursive: true })
  log(`created: ${rel}`)
}

function ensureFile(filePath, content, { dryRun, log, relBase }) {
  const rel = path.relative(relBase, filePath)
  if (fs.existsSync(filePath)) {
    log(`exists, skipping: ${rel}`)
    return
  }
  if (dryRun) {
    log(`would create: ${rel}`)
    return
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content)
  log(`created: ${rel}`)
}

function parseArgs(argv) {
  const result = { vault: null, modules: [], dryRun: false }
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--vault') {
      i += 1
      result.vault = argv[i]
      if (!result.vault) {
        return { error: 'atlas init: --vault requires a value' }
      }
    } else if (arg === '--modules') {
      i += 1
      const value = argv[i]
      if (!value) {
        return { error: 'atlas init: --modules requires a comma-separated value' }
      }
      result.modules = value
        .split(',')
        .map((name) => name.trim())
        .filter(Boolean)
    } else if (arg === '--dry-run') {
      result.dryRun = true
    } else {
      return { error: `atlas init: unknown option "${arg}"` }
    }
  }
  return result
}

/**
 * Run `atlas init`. Returns a process exit code: 0 success, 1 usage error,
 * 2 filesystem error. Never throws.
 *
 * @param {string[]} argv arguments after "init" (e.g. ['--dry-run'])
 * @param {{ cwd?: string, stdout?: { write: Function }, stderr?: { write: Function } }} [opts]
 * @returns {number}
 */
export function runInit(argv, opts = {}) {
  const cwd = opts.cwd ?? process.cwd()
  const stdout = opts.stdout ?? process.stdout
  const stderr = opts.stderr ?? process.stderr
  const log = (msg) => stdout.write(`${msg}\n`)

  const parsed = parseArgs(argv)
  if (parsed.error) {
    stderr.write(`${parsed.error}\n`)
    return 1
  }

  const unknownModules = parsed.modules.filter((name) => !MODULE_NAMES.includes(name))
  if (unknownModules.length > 0) {
    stderr.write(`atlas init: unknown module(s): ${unknownModules.join(', ')}\n`)
    stderr.write(`Valid modules: ${MODULE_NAMES.join(', ')}\n`)
    return 1
  }

  try {
    const root = findRepoRoot(cwd)
    const effectiveRoot = root ?? path.resolve(cwd)
    if (!root) {
      log('warning: no .git found above the current directory; scaffolding relative to cwd')
    }

    const dryRun = parsed.dryRun
    const ctx = { dryRun, log, relBase: effectiveRoot }

    const existingVault = findVaultDir(effectiveRoot)
    const vaultName = parsed.vault ?? `${path.basename(effectiveRoot)}-atlas`
    const vaultDir = existingVault ?? path.join(effectiveRoot, vaultName)

    if (existingVault) {
      log(
        `existing vault detected at ${path.relative(effectiveRoot, vaultDir)}/; running in additive mode`,
      )
    }

    // Core skeleton (SPEC.md §2)
    for (const rel of CORE_DIRS) {
      ensureDir(path.join(vaultDir, rel), ctx)
    }

    const vaultReadme = fs.readFileSync(path.join(TEMPLATES_DIR, 'vault', 'README.md'), 'utf8')
    ensureFile(path.join(vaultDir, 'README.md'), vaultReadme, ctx)
    ensureFile(path.join(vaultDir, 'map', 'index.md'), INDEX_PLACEHOLDER, ctx)

    // Note templates, copied (not referenced) with {{DATE}} substituted.
    const date = todayDate()
    for (const name of NOTE_TEMPLATE_NAMES) {
      const raw = fs.readFileSync(path.join(TEMPLATES_DIR, 'notes', name), 'utf8')
      const substituted = raw.replaceAll('{{DATE}}', date)
      ensureFile(path.join(vaultDir, 'templates', name), substituted, ctx)
    }

    // Optional modules
    for (const name of parsed.modules) {
      MODULE_ACTIONS[name](vaultDir, ctx)
    }

    // atlas.config.json at the REPO root (not the vault root)
    const configTemplate = fs.readFileSync(
      path.join(TEMPLATES_DIR, 'config', 'atlas.config.json'),
      'utf8',
    )
    const vaultRel = path.relative(effectiveRoot, vaultDir) || '.'
    const configObj = JSON.parse(configTemplate.replace('{{VAULT}}', vaultRel))
    for (const name of parsed.modules) {
      configObj.modules[name] = true
    }
    const configJson = `${JSON.stringify(configObj, null, 2)}\n`
    ensureFile(path.join(effectiveRoot, 'atlas.config.json'), configJson, ctx)

    log('')
    log('Next steps:')
    log('  - Seed 4-8 zone cards, one per coherent subsystem, under map/zones/.')
    log('  - Keep status: seeded + verifiedAt: unverified until a human verifies each card.')
    log('  - Add the CLAUDE.md/AGENTS.md on-ramp block (see Plan 004).')
    log('  - Run `atlas check` once available (see Plan 003).')

    return 0
  } catch (err) {
    stderr.write(`atlas init: filesystem error: ${err.message}\n`)
    return 2
  }
}
