import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadConfig, PROFILES } from './config.mjs'
import { findRepoRoot, findVaultDir } from './detect.mjs'
import { defaultState, STATE_FILE } from './state.mjs'

const PACKAGE_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const TEMPLATES_DIR = path.join(PACKAGE_ROOT, 'templates')

const NOTE_TEMPLATE_NAMES = [
  'zone.md',
  'flow.md',
  'decision.md',
  'spec.md',
  'plan.md',
  'program.md',
  'idea.md',
  'debt.md',
  'pillar.md',
  'report.md',
]

/**
 * SPEC.md §2 core skeleton, resolved through `config.folders` so a
 * remapped vault (e.g. `"ideas": "notes/sparks"`) scaffolds at the mapped
 * location instead of the default one.
 *
 * @param {Record<string, string>} folders
 * @returns {string[]}
 */
function coreDirs(folders) {
  return [
    folders.zones,
    folders.decisions,
    folders.specs,
    folders.plans,
    folders.ideas,
    folders.techDebt,
    folders.templates,
  ]
}

const INDEX_PLACEHOLDER = `<!-- GENERATED by atlas — do not hand-edit -->

| Zone | Status | Freshness | Summary |
|------|--------|-----------|---------|
`

const BACKLOG_TEMPLATE = `# BACKLOG

Multi-session coordination. Claim a row with 🟡 before starting work on it,
record a **Lands** field (branch name, or \`docs→main\` for vault-only work),
and mark it ✅ with a reference once done.

Status legend: 🟡 claimed · ⬜ open · ✅ done

## Track A (main, sequential)

- [ ] **A1 — <mission>**

## Track D (side-missions, parallel-safe)

| ID | Status | Mission | Lands |
|----|--------|---------|-------|
`

const DRAFTS_README = `# drafts

Human scratch space. Excluded from agent retrieval by default (see
\`atlas.config.json\` → \`retrieval.excludeFromSearch\`).
`

const REPORTS_README = `# Reports

Point-in-time snapshots — what something *was* at one moment, derived from
code, git history, or backlog state. A report commits to nothing and
supersedes nothing; once written it is frozen. Forward-looking truth lives
in plans, specs, and decisions.

Naming: \`YYYY-MM-DD-<topic>.md\`

Frontmatter contract:
\`\`\`yaml
type: report
status: snapshot
summary: "One-paragraph abstract of the snapshot."
zones: [zone-ids, touched]
covers: path/or/artifact/the/report/describes
created: YYYY-MM-DD
updated: YYYY-MM-DD
\`\`\`
`

// Each action reads its target directory from `ctx.folders` (set by
// runInit from the resolved config) rather than a hardcoded literal —
// `BACKLOG.md` and module-relative `README.md` files aren't part of the
// `folders` map (SPEC.md lists them as fixed top-level vault files).
const MODULE_ACTIONS = {
  flows: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.flows), ctx)
  },
  programs: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.programs), ctx)
  },
  vision: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.vision), ctx)
  },
  reference: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.reference), ctx)
  },
  archive: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.archive), ctx)
  },
  reports: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.reports), ctx)
    ensureFile(path.join(vaultDir, ctx.folders.reports, 'README.md'), REPORTS_README, ctx)
  },
  backlog: (vaultDir, ctx) => {
    ensureFile(path.join(vaultDir, 'BACKLOG.md'), BACKLOG_TEMPLATE, ctx)
  },
  drafts: (vaultDir, ctx) => {
    ensureDir(path.join(vaultDir, ctx.folders.drafts), ctx)
    ensureFile(path.join(vaultDir, ctx.folders.drafts, 'README.md'), DRAFTS_README, ctx)
  },
}

const MODULE_NAMES = Object.keys(MODULE_ACTIONS)

function todayDate() {
  return new Date().toISOString().slice(0, 10)
}

function ensureDir(dirPath, { dryRun, log, relBase }) {
  const rel = `${path.relative(relBase, dirPath)}/`
  if (fs.existsSync(dirPath)) {
    log(`exists, skipping: ${rel}`)
    return
  }
  if (dryRun) {
    log(`would create: ${rel}`)
    return
  }
  fs.mkdirSync(dirPath, { recursive: true })
  log(`created: ${rel}`)
}

function ensureFile(filePath, content, { dryRun, log, relBase }) {
  const rel = path.relative(relBase, filePath)
  if (fs.existsSync(filePath)) {
    log(`exists, skipping: ${rel}`)
    return
  }
  if (dryRun) {
    log(`would create: ${rel}`)
    return
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content)
  log(`created: ${rel}`)
}

function parseArgs(argv) {
  const result = { vault: null, modules: [], dryRun: false, profile: null }
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--vault') {
      i += 1
      result.vault = argv[i]
      if (!result.vault) {
        return { error: 'atlas init: --vault requires a value' }
      }
    } else if (arg === '--profile') {
      i += 1
      result.profile = argv[i]
      if (!result.profile) {
        return { error: 'atlas init: --profile requires code|operator' }
      }
      if (!PROFILES[result.profile]) {
        return {
          error: `atlas init: unknown profile "${result.profile}" (use code|operator)`,
        }
      }
    } else if (arg === '--modules') {
      i += 1
      const value = argv[i]
      if (!value) {
        return { error: 'atlas init: --modules requires a comma-separated value' }
      }
      result.modules = value
        .split(',')
        .map((name) => name.trim())
        .filter(Boolean)
    } else if (arg === '--dry-run') {
      result.dryRun = true
    } else {
      return { error: `atlas init: unknown option "${arg}"` }
    }
  }
  return result
}

/**
 * Run `atlas init`. Returns a process exit code: 0 success, 1 usage error,
 * 2 filesystem error. Never throws.
 *
 * @param {string[]} argv arguments after "init" (e.g. ['--dry-run'])
 * @param {{ cwd?: string, stdout?: { write: Function }, stderr?: { write: Function } }} [opts]
 * @returns {number}
 */
export function runInit(argv, opts = {}) {
  const cwd = opts.cwd ?? process.cwd()
  const stdout = opts.stdout ?? process.stdout
  const stderr = opts.stderr ?? process.stderr
  const log = (msg) => stdout.write(`${msg}\n`)

  const parsed = parseArgs(argv)
  if (parsed.error) {
    stderr.write(`${parsed.error}\n`)
    return 1
  }

  const unknownModules = parsed.modules.filter((name) => !MODULE_NAMES.includes(name))
  if (unknownModules.length > 0) {
    stderr.write(`atlas init: unknown module(s): ${unknownModules.join(', ')}\n`)
    stderr.write(`Valid modules: ${MODULE_NAMES.join(', ')}\n`)
    return 1
  }

  try {
    const root = findRepoRoot(cwd)
    const effectiveRoot = root ?? path.resolve(cwd)
    if (!root) {
      log('warning: no .git found above the current directory; scaffolding relative to cwd')
    }

    const dryRun = parsed.dryRun

    // A pre-existing atlas.config.json (hand-authored or from an earlier
    // `atlas init`) drives where additive-mode scaffolding lands — a repo
    // whose config remaps `folders.ideas` to `notes/sparks` gets that
    // directory, not the default `ideas/`. A fresh repo has no config yet,
    // so this resolves to the same defaults CORE_DIRS/MODULE_ACTIONS used
    // before folder indirection existed.
    const folders = loadConfig(effectiveRoot).folders
    const ctx = { dryRun, log, relBase: effectiveRoot, folders }

    const existingVault = findVaultDir(effectiveRoot)
    const vaultName = parsed.vault ?? `${path.basename(effectiveRoot)}-atlas`
    const vaultDir = existingVault ?? path.join(effectiveRoot, vaultName)

    if (existingVault) {
      log(
        `existing vault detected at ${path.relative(effectiveRoot, vaultDir)}/; running in additive mode`,
      )
    }

    // Core skeleton (SPEC.md §2)
    for (const rel of coreDirs(folders)) {
      ensureDir(path.join(vaultDir, rel), ctx)
    }

    const vaultReadme = fs.readFileSync(path.join(TEMPLATES_DIR, 'vault', 'README.md'), 'utf8')
    ensureFile(path.join(vaultDir, 'README.md'), vaultReadme, ctx)
    ensureFile(path.join(vaultDir, 'map', 'index.md'), INDEX_PLACEHOLDER, ctx)

    // Note templates, copied (not referenced) with {{DATE}} substituted.
    const date = todayDate()
    for (const name of NOTE_TEMPLATE_NAMES) {
      const raw = fs.readFileSync(path.join(TEMPLATES_DIR, 'notes', name), 'utf8')
      const substituted = raw.replaceAll('{{DATE}}', date)
      ensureFile(path.join(vaultDir, folders.templates, name), substituted, ctx)
    }

    // Profile → default modules (operator turns on ledger modules)
    const profileName = parsed.profile || 'code'
    const profileMods = PROFILES[profileName]?.modules || {}
    const modulesFromProfile = Object.entries(profileMods)
      .filter(([, on]) => on)
      .map(([name]) => name)
    const modules = [...new Set([...modulesFromProfile, ...parsed.modules])]

    // Optional modules
    for (const name of modules) {
      MODULE_ACTIONS[name](vaultDir, ctx)
    }

    // atlas.config.json at the REPO root (not the vault root)
    const configTemplate = fs.readFileSync(
      path.join(TEMPLATES_DIR, 'config', 'atlas.config.json'),
      'utf8',
    )
    const vaultRel = path.relative(effectiveRoot, vaultDir) || '.'
    const configObj = JSON.parse(configTemplate.replace('{{VAULT}}', vaultRel))
    configObj.profile = profileName
    for (const name of modules) {
      configObj.modules[name] = true
    }
    const configJson = `${JSON.stringify(configObj, null, 2)}\n`
    ensureFile(path.join(effectiveRoot, 'atlas.config.json'), configJson, ctx)

    // Provenance lockfile — create-if-missing only; never regress wired state.
    const stateJson = `${JSON.stringify(defaultState({ modules: [...modules] }), null, 2)}\n`
    ensureFile(path.join(effectiveRoot, STATE_FILE), stateJson, ctx)

    log('')
    log(`Profile: ${profileName}`)
    log('Next steps:')
    log('  - Seed 4-8 zone cards, one per coherent subsystem, under map/zones/.')
    log('  - Keep status: seeded + verifiedAt: unverified until a human verifies each card.')
    if (profileName === 'operator') {
      log('  - Operator profile: empty owns.globs allowed (policy zones); still prefer real globs when code exists.')
    }
    log('  - Add a short CLAUDE.md/AGENTS.md on-ramp block pointing agents at map/index.md.')
    log('  - Run `atlas stamp <slug>` once a card is reviewed, then `atlas build` / `atlas check`.')
    log('  - Search: `atlas search <terms>` (rg-first portable floor).')

    return 0
  } catch (err) {
    stderr.write(`atlas init: filesystem error: ${err.message}\n`)
    return 2
  }
}
